version: '3'
services:
  mysql:
    container_name: frame-server-mysql
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=frame-server
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    volumes:
      - /Users/jinpengh/Desktop/jinpengh/data/frame-server-mysql:/var/lib/mysql